backend:
  # name: git-gateway
  name: github
  repo: amaphn/reseau-amap-hn.com
  branch: staging
# when using the default proxy server port
# http://localhost/amap-directory/admin/#/collections/page
# npx netlify-cms-proxy-server
# local_backend: true
locale: fr
site_url: http://staging.reseau-amap-hn.com/?key=vcgZFowdrfHbdYBua2ahPQ
custom_logo: http://staging.reseau-amap-hn.com/assets/logo/logo-amap-haut-normand-long.svg
slug: 
  encoding: ascii
  # clean_accents: true
media_folder: telechargements
public_folder: telechargements
# publish_mode: editorial_workflow
collections:
  - name: pages
    label: Pages
    label_singular: Page
    description: Pages de premier niveau
    folder: pages
    media_folder: /pages/images
    public_folder: /content/pages/images
    # cf. editorial_workflow
    # publish: false 
    summary: "{{title}} {{draft | ternary('✘', '✔︎')}}"
    sortable_folder: ['title']
    view_filters:
      - label: Publié
        field: draft
        pattern: false
      - label: Brouillon
        field: draft
        pattern: true
    create: true
    fields: 
      - name: body
        label: Contenu
        widget: markdown
        required: false
      - name: title
        label: Titre
        widget: string
        hint: Pour un titre SEO optimal, ne pas dépasser 70 caractères.
      - name: short_title
        label: Titre court
        widget: string
        required: false
      - name: description
        label: Description
        hint: Pour une description SEO optimale, ne pas dépasser 160 carctères.
        widget: text
        required: false
      - name: draft
        label: Brouillon
        widget: boolean
        default: false
        required: false
  - name: informations
    label: Informations
    label_singular: Information
    summary: "{{title}} {{draft | ternary('✘', '✔︎')}}"
    description: >
      Pages informations
    folder: /pages/informations
    # slug: '{{slug}}'
    # path: '{{year}}/{{month}}/{{slug}}'
    media_folder: /pages/informations/images
    public_folder: /content/pages/informations/images
    # summary: "{{dirname}}/{{filename}} ({{title}})"
    sortable_fields: ['title']
    view_filters:
      - label: Brouillon
        field: draft
        pattern: true
    create: true
    # nested:
    #   depth: 5
    # # meta: { path: { widget: string, label: 'Path', default: '/', index_file: 'index' } }
    fields:   
      - name: body
        label: Contenu
        widget: markdown
        required: false
      - name: title
        label: Titre
        widget: string
      - name: short_title
        label: Titre court
        widget: string
        required: false
      - name: description
        label: Description
        widget: text
        required: false  
      - name: downloads
        label: Téléchargements
        widget: list
        summary: '{{text}}'
        label_singular: Fichier
        minimize_collapsed: true
        required: false
        fields:
          - name: text
            label: Texte
            widget: string
          - name: path
            label: Fichier
            widget: file
      - name: draft
        label: Brouillon
        widget: boolean
        default: false
        required: false            
  - name: blog
    label: Articles
    label_singular: Article
    description: >
      Pages standard
    folder: posts
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    media_folder: /posts/images
    public_folder: /content/posts/images
    summary: "{{featured | ternary('★', '')}} {{title}} ({{filename}}) {{draft | ternary('✘', '✔︎')}}"
    sortable_fields: ['title', 'date', 'commit_date']
    view_filters:
      - label: Mis en avant
        field: featured
        pattern: true
      - label: Brouillon
        field: draft
        pattern: true
    view_groups:
      - label: Année
        field: date
        pattern: \d{4}
    create: true
    fields: 
      - name: body
        label: Contenu
        widget: markdown
        required: false
      - name: summary
        label: Résumé
        widget: text
        required: false
      - name: title
        label: Titre de la page
        widget: string
      - name: date
        label: Date de publication
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
        format: DD-MM-YYYY
      - name: cover
        label: Couverture
        widget: file
        required: false
      - name: publish
        label: Publier
        widget: boolean
        default: true
        required: false
      - name: featured
        label: Mettre en avant
        widget: boolean
        default: false
        required: false
      - label: Catégories
        name: category
        hint: Ajoutez de nouvelles catégories via le menu principal "Catégories"
        widget: relation
        required: false
        collection: categories
        search_fields: ['name']
        value_field: "{{slug}}"
        display_fields: ['name']
      - label: SEO
        name: seo
        widget: object
        collapsed: true
        fields:
        - name: short_title
          label: Titre court
          widget: string
          required: false
        - name: description
          label: Description
          widget: text
          required: false
  - name: categories
    label: Catégories
    label_singular: Categorie
    description: Catégories pour classer les contenus.
    folder: categories
    identifier_field: name
    create: true
    editor:
      preview: false
    fields:
      - name: name
        label: Name
        widget: string
      - name: description
        label: Description
        widget: text
        required: false
      - name: hide
        label: Masquer l'étiquette
        widget: boolean
        default: false
        required: false
      - name: featured-image
        label: Image de présentation
        widget: object
        minimize_collapsed: true
        fields: 
          - name: file
            label: Fichier
            widget: file
            required: false
          - name: alt-text
            label: Texte alternatif
            widget: string
            required: false
          - name: caption
            label: Légende
            widget: string
            required: false
          - name: credit
            label: Crédit
            widget: string
            required: false
      - name: seo
        label: SEO
        widget: object
        collapsed: true
        required: false
        fields:
          - name: title
            label: Titre de la page
            widget: string
            required: false
          - name: description
            label: Description de la page
            widget: text
            required: false
  - name: configuration
    label: Configuration
    description: Configuration du site
    files: 
      - name: global
        label: Générale
        file: configuration/global.json
        editor: 
          preview: false
        fields:
          - name: name
            label: Nom
            widget: string
          - name: description
            label: Description
            widget: text
            hint: Description SEO, 160 signes recommandé.
          - name: url
            label: URL
            widget: string
          - name: email
            label: Email
            widget: string
            required: false
          - name: facebook
            label: Facebook
            widget: string
            required: false
          - name: address
            label: Adresse
            widget: object
            collapsed: true
            fields:
              - name: name
                label: Nom
                widget: string
                required: false
              - name: street
                label: Rue
                widget: string
                required: false
              - name: zipcode
                label: Code postal
                widget: string
                required: false
              - name: city
                label: Ville
                widget: string
                required: false
      - name: home
        label: Accueil
        file: pages/home.md
        editor:
          preview: false
        fields:
          - name: summary
            label: Présentation
            widget: markdown
          - name: sections
            label: Sections
            widget: list
            max: 3
            collapsed: true
            fields: 
              - name: section
                label:  Section
                widget: markdown
      - name: footer
        label: Pied de page
        file: configuration/footer.json
        editor:
          preview: false
        fields:
          - name: links
            label: Liens
            widget: list
            summary: '{{text}}'
            label_singular: Lien
            minimize_collapsed: true
            required: false
            fields: 
              - name: text
                label: Texte
                widget: string
              - name: url
                label: URL
                widget: string
          - name: partners
            label: Partenaires
            widget: list
            summary: '{{name}}'
            label_singular: Partenaire
            minimize_collapsed: true
            required: false
            fields:
              - name: name
                label: Nom
                widget: string
              - name: logo
                label: Logo
                widget: file
              - name: url
                label: URL
                widget: string